### PR TITLE
gitignore: ignore editor's temporary files

### PR DESCRIPTION
**Pull request by gucio321**

### CODE REVIEW

**Comment by gucio321** [comment]
plz, could it be merged?
It is really annoying to care about these files when `git add`

**Comment by gucio321** [comment]
oh man! what happend with that CI???
```console
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    19  100    19    0     0     54      0 --:--:-- --:--:-- --:--:--    54
gpg: no valid OpenPGP data found.
deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr jammy

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

we really need to use Makefile instead of just!

**Comment by eliasdaler** [comment]
Really strange. Try rebasing on latest master and try again.

**Comment by gucio321** [comment]
> Really strange. Try rebasing on latest master and try again.

well, it decided to start working again.

**Review by eliasdaler — APPROVED** [review]

**Pull request merged**
