### PR TITLE
typedefs generation

### PR DESCRIPTION
**Pull request by gucio321**
This pull requests contains the following changes:
- remove current structs generator
- generate structs (and other types) basing on typedefs_dict.json (instead of structs_and_enums.json)
- upgrade some types to be more meaningful for go users (for example textureID became `type TextureID uint32`)

### CODE REVIEW

**Comment by gucio321** [comment]
- https://github.com/golang/go/issues/64111

**Comment by gucio321** [comment]
also ref: https://forum.golangbridge.org/t/fatal-error-invalid-pointer-found-on-stack/33579

**Comment by ptxmac** [comment]
> * upgrade some types to be more meaningful for go users (for example textureID became `type TextureID uint32`)

I don't see this change in the PR? It's still 
```go
type TextureID struct {
	Data unsafe.Pointer
}
```

which is very inconvenient to work with

**Comment by gucio321** [comment]
> I don't see this change in the PR? It's still

yep, it is unsafe.Pointer but I thnk to make it `uintptr` instead
Would it be better?

**Comment by AllenDang** [comment]
I remember I choose unsafe.Pointer for a reason, like race tracing issue.

**Comment by gucio321** [comment]
Yeah but this makes my feel a bit crazy.. https://github.com/golang/go/issues/64111

**Comment by ptxmac** [comment]
> > I don't see this change in the PR? It's still
> 
> yep, it is unsafe.Pointer but I thnk to make it `uintptr` instead Would it be better?

Yeah, that would work, right now I'm using something like this
```go
		ptr := unsafe.Pointer(uintptr(b.Tex.GetRef()))
		ImageV(TextureID{Data: ptr}, // ...

```

**Comment by ptxmac** [comment]
> I remember I choose unsafe.Pointer for a reason, like race tracing issue.

How would that work? 🤔

**Comment by gucio321** [comment]
well it doesn't compile unfortunately...
And, since GO Developers refuse to cooperate unfortunatley (AGAIN)
- see: https://github.com/golang/go/issues/64111
I see no good way at this point.

We can either use uintptr and fail each `-race` build or leafe texture as unsafe.pointer and suffer from the issue above...

**Comment by 38dh91** [comment]
@gucio321 awesome! Your PR fixed not only font builder, but also clipper too. Thx a lot!

**Comment by gucio321** [comment]
Great to hear this! I deffinitely need to finish this and merge to master!

**Comment by gucio321** [comment]
its mostly done, now I'm getting "works for me" issue.
Gonna get back here tomorrow.

**Comment by gucio321** [comment]
I pushed some fixes. I hope this will work soon.

**Comment by ptxmac** [comment]
@gucio321 Thanks for the effort! This PR took a while to get done, but it fixed all the problems I had workarounds for!

**Pull request merged**
