### PR TITLE
Revert "Merge pull request #18 from gucio321/use-submodules"

### LINKED ISSUE #43: module: build failure
Hi, I'm having trouble building the latest code
```shell
cd examples
go run .
```
```console
# github.com/AllenDang/cimgui-go
In file included from ./cimplot_wrapper.h:3,
                 from ./cimplot_structs_accessor.h:3,
                 from ../cimplot_funcs.go:4:
./cimplot/cimplot.h:7:10: fatal error: cimgui.h: No such file or directory
    7 | #include "cimgui.h"
      |          ^~~~~~~~~~
compilation terminated.
```

### PR DESCRIPTION
**Pull request by gucio321**
This reverts commit 47f2614d4ab3de2153f1b619dbe81df899525c36, reversing changes made to c48968810967381c00140243c06a2f066514c4f2.

### CODE REVIEW

**Comment by gucio321** [comment]
sadly, its rather not a perfect way to fix the issue :smile:
let me think

**Comment by eliasdaler** [comment]
Let's not jump here, the work done here is good. We might fix it better.

**Comment by gucio321** [comment]
I also wouldn't feel into merging this PR.
I've just opened it because clicking "revert" on #18 didn't work

Go ahead, close this and move discussion to #43

**Comment by gucio321** [comment]
I feel terrible about it, but IMO it is the best solution of  #43 for now :cry:

**Review by eliasdaler — APPROVED** [review]
Well, what can you do... "go get" doesn't fetch git submodules so we have no choice here.

**Comment by gucio321** [comment]
> Well, what can you do... "go get" doesn't fetch git submodules so we have no choice here.

@eliasdaler in fact, `go get` does, but `go mod vendor` removes them

**Pull request merged**
