### PR TITLE
Cimgui updater

### PR DESCRIPTION
**Pull request by gucio321**
## CHANGELOG

during discussing vendoring issue, there was an idea to create a CI that will update imgui code. This is a first step - a Makefile rule that updates cimgui dependencies:
- [x] add `update` rule that updates c code
- [x] make the C code a go package (#34) 
- [x] since now, the project layout is changed a bit:
       - all C code is placed inside `cimgui` directory (name to be discussed)
       - C++ upstreams are also in that directory
       - {prefix}_templates contains _only_ the json deffinitions of the functions
- [x] cimgui/VERSION.txt holds information about versions of dependencies
- [x] I've changed type of ImWchar (in `extra_types.go`) so that it seems work better... (need to test)
- [ ] make it all compile :smile:

## reference:

update #34, #90

### CODE REVIEW

**Comment by gucio321** [comment]
some C stuff seems to be broken after update.

**Comment by gucio321** [comment]
meh, linker crash :confused:
@AllenDang What do you think about this PR? Is it good idea?
Also, what has been done to make this cimgui working here?

**Comment by AllenDang** [comment]
I think auto updater is kind of tricky, since we have some manual code in wrapper, auto update might introduce bugs in futrue and we might not be able to notice intime.

**Comment by gucio321** [comment]
> I think auto updater is kind of tricky, since we have some manual code in wrapper,

yeah and I think we shouldn't. cimgui should not be modified anyhow imao

**Comment by AllenDang** [comment]
Lets make it work!

**Comment by gucio321** [comment]
Gonna try but getting strange linker failure.

**Comment by gucio321** [comment]
:thinking: No idea... Trying to run gcc with `-v` to see if it shows what exactly crashes

**Comment by gucio321** [comment]
<details>

```console
# github.com/AllenDang/cimgui-go/examples
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-m64' '-s' '-o' '/tmp/go-build2756194537/b001/exe/examples' '-rdynamic' '-O2' '-g' '-O2' '-g' '-no-pie' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccpByQk0.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o $WORK/b001/exe/examples -s /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --compress-debug-sections=zlib /tmp/go-link-2714590394/go.o /tmp/go-link-2714590394/000000.o /tmp/go-link-2714590394/000001.o /tmp/go-link-2714590394/000002.o /tmp/go-link-2714590394/000003.o /tmp/go-link-2714590394/000004.o /tmp/go-link-2714590394/000005.o /tmp/go-link-2714590394/000006.o /tmp/go-link-2714590394/000007.o /tmp/go-link-2714590394/000008.o /tmp/go-link-2714590394/000009.o /tmp/go-link-2714590394/000010.o /tmp/go-link-2714590394/000011.o /tmp/go-link-2714590394/000012.o /tmp/go-link-2714590394/000013.o /tmp/go-link-2714590394/000014.o /tmp/go-link-2714590394/000015.o /tmp/go-link-2714590394/000016.o /tmp/go-link-2714590394/000017.o /tmp/go-link-2714590394/000018.o /tmp/go-link-2714590394/000019.o /tmp/go-link-2714590394/000020.o /tmp/go-link-2714590394/000021.o /tmp/go-link-2714590394/000022.o /tmp/go-link-2714590394/000023.o /tmp/go-link-2714590394/000024.o /tmp/go-link-2714590394/000025.o /tmp/go-link-2714590394/000026.o /tmp/go-link-2714590394/000027.o /tmp/go-link-2714590394/000028.o /tmp/go-link-2714590394/000029.o /tmp/go-link-2714590394/000030.o /workspaces/cimgui-go/lib/linux/x64/libglfw3.a -ldl -lGL -lX11 /workspaces/cimgui-go/lib/linux/x64/cimgui.a -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImFontAtlas_GetGlyphRangesGreek':
/tmp/go-build/cgo-gcc-prolog:1530: undefined reference to `ImFontAtlas_GetGlyphRangesGreek'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsKeyDown_Nil':
/tmp/go-build/cgo-gcc-prolog:6942: undefined reference to `igIsKeyDown_Nil'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsKeyPressed_Bool':
/tmp/go-build/cgo-gcc-prolog:6963: undefined reference to `igIsKeyPressed_Bool'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsKeyReleased_Nil':
/tmp/go-build/cgo-gcc-prolog:6983: undefined reference to `igIsKeyReleased_Nil'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsMouseClicked_Bool':
/tmp/go-build/cgo-gcc-prolog:7004: undefined reference to `igIsMouseClicked_Bool'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsMouseDown_Nil':
/tmp/go-build/cgo-gcc-prolog:7044: undefined reference to `igIsMouseDown_Nil'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igIsMouseReleased_Nil':
/tmp/go-build/cgo-gcc-prolog:7125: undefined reference to `igIsMouseReleased_Nil'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImGuiKeyOwnerData_destroy':
/tmp/go-build/cgo-gcc-prolog:2463: undefined reference to `ImGuiKeyOwnerData_destroy'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImGuiKeyRoutingData_destroy':
/tmp/go-build/cgo-gcc-prolog:2475: undefined reference to `ImGuiKeyRoutingData_destroy'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImGuiKeyRoutingTable_destroy':
/tmp/go-build/cgo-gcc-prolog:2487: undefined reference to `ImGuiKeyRoutingTable_destroy'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igPopTabStop':
/tmp/go-build/cgo-gcc-prolog:7687: undefined reference to `igPopTabStop'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igPushTabStop':
/tmp/go-build/cgo-gcc-prolog:7884: undefined reference to `igPushTabStop'
/usr/bin/ld: /tmp/go-link-2714590394/000003.o: in function `_cgo_d3cbe02b35b2_Cfunc_igSeparatorText':
/tmp/go-build/cgo-gcc-prolog:8091: undefined reference to `igSeparatorText'
/usr/bin/ld: /tmp/go-link-2714590394/000005.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImPlotAnnotation_ImPlotAnnotation':
/tmp/go-build/cgo-gcc-prolog:193: undefined reference to `ImPlotAnnotation_ImPlotAnnotation'
/usr/bin/ld: /tmp/go-link-2714590394/000005.o: in function `_cgo_d3cbe02b35b2_Cfunc_ImPlotAnnotation_destroy':
/tmp/go-build/cgo-gcc-prolog:208: undefined reference to `ImPlotAnnotation_destroy'
/usr/bin/ld: /tmp/go-link-2714590394/000014.o: in function `wrap_igIsKeyPressed_Bool':
/workspaces/cimgui-go/cimgui_wrapper.cpp:141: undefined reference to `igIsKeyPressed_Bool'
/usr/bin/ld: /tmp/go-link-2714590394/000014.o: in function `wrap_igIsMouseClicked_Bool':
/workspaces/cimgui-go/cimgui_wrapper.cpp:142: undefined reference to `igIsMouseClicked_Bool'
collect2: error: ld returned 1 exit status
```

</details>

**Comment by gucio321** [comment]
superseeded by #122

**Pull request closed without merging**
