### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by gucio321**
progress on #27 
- funcs
- enum deffinitions

### CODE REVIEW

**Comment by gucio321** [comment]
I think, I'll fix the whole #27 here as only struct comments left.

**Comment by gucio321** [comment]
ok, done

**Comment by gucio321** [comment]
oh wait, it needs generation i think

**Comment by gucio321** [comment]
well it seems that I broke something...

**Comment by gucio321** [comment]
ref: https://github.com/cimgui/cimgui/issues/239

**Comment by gucio321** [comment]
The issue is closed, so let me suppose this will work now

**Comment by gucio321** [comment]
ok @AllenDang ready to review.

**Review by AllenDang — APPROVED** [review]
Good work!

**Pull request merged**
