### PR TITLE
Split module to separated packages

### LINKED ISSUE #25: Idea: move implot functions to a separate package
Hello. When working on #20, I've noticed that some enum names can clash if we remove prefixes, e.g. ImAxis from implot and ImGuiAxis from Dear ImGui.

This got me thinking... what if we move all implot things to a directory called "implot" and call this package "implot as well"? This way, people would be able to do this:

```go
import "github.com/AllenDang/cimgui-go/implot"

// later in code
implot.SomeFunc()
```

and people who don't use implot won't get their autocomplete suggestions polluted by implot funcs/enums/structs if they don't want to use them.

### PR DESCRIPTION
**Pull request by gucio321**
Hi everyone!
Here I present a whole-new layout of cimgui-go.
This was discussed in, and will fix #25 

Now, instead of having everything in cimgui-go package, there are 4 smaller packages for each plugin.
In theory, it also reduces build time as it allows to parallelize implot, imnodes and immarkdown build.
<details><summary>results</summary>
on main:

```console
real	2m32.649s
user	3m5.343s
sys	0m6.430s
```

on this PR
```console
real	2m32.279s
user	3m6.522s
sys	0m6.435s
```

tested on ebiten example with `time go build -a -v`
</details>

@AllenDang this is a quite large change so I'll let you review and merge

### CODE REVIEW

**Comment by gucio321** [comment]
@AllenDang maybe we should tag current master and publish some release as this pr is done is done?
I'd suggest `v1.0.0` as I don't expect any backward-incompatible changes in the future, however we might want to wait with v1 for #224. If so we can release `v0.1.0` which doesn't have to keep up with any compatibility rules.

**Comment by AllenDang** [comment]
> @AllenDang maybe we should tag current master and publish some release as this pr is done is done? I'd suggest `v1.0.0` as I don't expect any backward-incompatible changes in the future, however we might want to wait with v1 for #224. If so we can release `v0.1.0` which doesn't have to keep up with any compatibility rules.

Agree, let's release v1.0.0!

**Comment by gucio321** [comment]
@AllenDang Release notes are ready. You should be able to see them.
Could you please take a look and check if everything is correct? https://github.com/AllenDang/cimgui-go/releases/tag/untagged-dff92b68e1384b851b54

**Comment by AllenDang** [comment]
@gucio321 Great work! I've read, awesome, looks everything is ready, please release it! Congratulations!

**Pull request merged**
