### PR TITLE
codegen: generate GO structs

### LINKED ISSUE #147: structs: why are they `uintptr`s?
We made most of our types `type TypeName uintptr`. I think it was a simplification (to make generator easier), but now we could improve it, couldn't we?
We can do it like we do with functions - we can use existing type/return wrappers to generate working `handle()` methods.
Any thoughts?

### PR DESCRIPTION
**Pull request by gucio321**
fix #147 
It tries to generate all struct fields. If it is impossible, it adds `TODO` comment and acts like it used to before (creates an unexported field called `data` of type `uintptr`)

current status:
for cimgui:
```console
2023-05-06 14:14:45	[INFO]:	28 of 105 structs fully generated (26.67 %)
```

for cimplot
```console
2023-05-06 14:14:47	[INFO]:	9 of 26 structs fully generated (34.62 %)
```

### CODE REVIEW

**Comment by gucio321** [comment]
I've created this draft, because development of this feature is quite advanced atm.
Sadly I hit https://github.com/golang/go/issues/59982 so need to wait for fixes in upstream.

**Comment by gucio321** [comment]
meh, I suppose this is another issue, which GO will not fix so we need workaround :-/

**Comment by gucio321** [comment]
well I think I can exclude structs with bitfields for now

**Comment by gucio321** [comment]
ok @AllenDang it is ready now.

**Comment by gucio321** [comment]
hmm, there is something wrong with tests...

**Comment by gucio321** [comment]
why do we use uintptr instead of unsafe.Pointer?

**Comment by gucio321** [comment]
also ref: https://pkg.go.dev/unsafe#Pointer

**Comment by gucio321** [comment]
yeah, @AllenDang it worked!
- https://github.com/AllenDang/cimgui-go/pull/170

**Comment by gucio321** [comment]
it worked :tada:
@AllenDang it is ready now

**Comment by gucio321** [comment]
hmm I see strange messages about "int" and similar - will check it

**Comment by AllenDang** [comment]
Is this pr ready?

**Comment by gucio321** [comment]
Yes

**Review by AllenDang — APPROVED** [review]
LGTM

**Pull request merged**
