### PR TITLE
Glfw submodule

### LINKED ISSUE #39: Make glfw a git submodule too
I guess that would also be a good thing to do after we've done #18 
@AllenDang, thoughts? cc: @gucio321

### PR DESCRIPTION
**Pull request by gucio321**
like @eliasdaler suggested, thirdparty/glfw should be a submodule like cimgui and cimplot

Upstream: https://github.com/glfw/glfw
Version/Revision: (current) master

fix #39

### CODE REVIEW

**Comment by gucio321** [comment]
strange... It seems that cimgui/cimplot submodules has been changed in my commits, but cant imagine why :smile:
git-submodules seems to be a bit tricky...

**Comment by eliasdaler** [comment]
Try going inside git submodule dir and checking out to the same commits as in master now. 
Also let’s move all submodules to the thirdparty dir for consistency.

**Comment by gucio321** [comment]
oh, thanx, it works!

**Comment by eliasdaler** [comment]
Looks good. Now the only thing left is to move cimgui and cimplot to "thirdparty".

**Comment by gucio321** [comment]
Well @eliasdaler  but i'd do that in a separate pr since it's not related to glfw and needs a bit more changes in justfile and workflows

**Comment by eliasdaler** [comment]
Okay, let's do it another PR. Merging.

**Pull request merged**
